CREATE TABLE IF NOT EXISTS `BA_RAID` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`R_NAME` VARCHAR(100) DEFAULT '',
	`R_DESCRIPTION` VARCHAR(200) DEFAULT '',
	`R_TYPE` INT,
	`R_TIMING` INT,
    `R_ATK_TYPE` INT,
	`R_DEF_TYPE` INT,
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(20),
	`UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` VARCHAR(20)
);