CREATE TABLE IF NOT EXISTS `BA_RAID_MEMBER` (
	`MEMBER_ID` INT,
	`RE_ID` INT,
	`RE_SCORE` INT DEFAULT 0,
	`RE_RANK` INT DEFAULT 0,
    `RE_DIFFICULTY` INT DEFAULT 0,
    `RE_TIMING` INT DEFAULT 0,
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(20),
	`UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` VARCHAR(20),
    UNIQUE (`MEMBER_ID`, `RE_ID`)
);