CREATE TABLE IF NOT EXISTS `BA_SCHOOL` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`NAME` VARCHAR(256) DEFAULT '',
	`DESCRIPTION` VARCHAR(1024) DEFAULT '',
	`ICON` VARCHAR(512) DEFAULT '',
	`COLOR` VARCHAR(10) DEFAULT '',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(20),
	`UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` VARCHAR(20),
	UNIQUE('NAME')
);