CREATE TABLE IF NOT EXISTS `BA_CLUB_MANAGE_WHITELIST` (
	`SERVER_ID` INT NOT NULL DEFAULT 0,
	`GUILD_ID` INT NOT NULL DEFAULT 0,
	`ID` INT NOT NULL DEFAULT 0,
	`TYPE` INT DEFAULT 0,
	`CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(20),
	`UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` VARCHAR(20),
	UNIQUE (`SERVER_ID`,`GUILD_ID`,`ID`,`TYPE`)
);