CREATE TABLE IF NOT EXISTS `BA_GUILD_MEMBER` (
	`SERVER_ID` INT,
	`GUILD_ID` INT,
	`MEMBER_ID` INT,
	`MEMBER_NICKNAME` VARCHAR(30),
	`MEMBER_IGN` VARCHAR(30),
	`MEMBER_JOINED_DATE` DATETIME,
	`CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(20),
	`UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` VARCHAR(20),
	UNIQUE (`SERVER_ID`,`GUILD_ID`,`MEMBER_ID`)
);