CREATE TABLE IF NOT EXISTS `KMS` (
	`ID` INT,
	`KEY` VARCHAR(100),
	`GUILD_DESCRIPTION` VARCHAR(100),
	`CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(20),
	`UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` VARCHAR(20),
	PRIMARY KEY (`ID`)
);