CREATE TABLE IF NOT EXISTS  `MISC` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`NAME` VARCHAR(100) DEFAULT '',
	`DESCRIPTION` VARCHAR(500) DEFAULT '',
	`TYPE` VARCHAR(100) DEFAULT '',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(20),
	`UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` VARCHAR(20),
    UNIQUE (`ID`, `TYPE`, `NAME`)
);