CREATE TABLE IF NOT EXISTS `DC_SERVER` (
	`SERVER_ID` INT,
	`SERVER_NAME` VARCHAR(100),
	`CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(20),
	`UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_BY` VARCHAR(20),
	PRIMARY KEY (`SERVER_ID`)
);