CREATE TABLE IF NOT EXISTS `DC_SERVER_SETTING` (
	`SERVER_ID` INT,
	`LOCALE` VARCHAR(10) DEFAULT 'en_US',
	`EN_DEF_ROLE` INT DEFAULT 0,
	`DEF_ROLE` INT,
	`CREATED_ON` DATETIME,
	`CREATED_BY` VARCHAR(20) DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_ON` DATETIME,
	`UPDATED_BY` VARCHAR(20) DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`SERVER_ID`)
);